pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    environment {
        GREETING = 'Hello Jenkins'
    }
    parameters {
            string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

            text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

            booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

            choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

            password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
        }

    options {
        timeout(time: 1, unit:'HOURS')
        disableConcurrentBuilds()
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building........'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.......'
            }
        }
        stage('Deploy') {
            steps {
                sh """
                    echo "Hello I am from shell script"
                    echo "$GREETING"
                    sleep 20
                    """
            }
        }
        stage('check params') {
            steps{
                sh """
                    echo "Hello ${params.PERSON}"
                    echo "Biography: ${params.BIOGRAPHY}"
                    echo "Toggle: ${params.TOGGLE}"
                    echo "choice: ${params.CHOICE}"
                    echo "Password: ${params.PASSWORD}"
                    echo "trigger is added"
                """
            }
        }
    }
    // post build
    post {
        always{
            echo 'We Will always Win again!'
        }
        failure {
            echo 'failure occured, inform the concerned teams over slack'
        }
        success {
            echo 'Confragulations on success build'
        }
    }
}