pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    environment {
    AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')    // Jenkins credential ID
    AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key') // Jenkins credential ID  
    AWS_DEFAULT_REGION    = 'us-east-1' // match your S3 backend region
    }
    options {
        timeout(time: 1, unit:'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick your choice')
    }
    stages {
        stage('terraform init') {
            steps {
                sh """
                    cd 01-vpc-creation
                    terraform init -reconfigure
                    """
            }
        }
        stage('terraform plan') {
            steps {
                sh """
                    cd 01-vpc-creation
                    terraform plan
                    """
            }
        }
        stage('Apply') {
            when {
                expression{
                    params.action == 'apply'
                }
            }
            // input {
            //     message "Should we continue Infra Creation?"
            //     ok "Yes, we should"
            // }
            steps {
                sh """
                    cd 01-vpc-creation
                    terraform apply -auto-approve
                    """
            }
        }
        stage('Destory') {
            when {
                expression{
                    params.action == 'destroy'
                }
            }
            // input {
            //     message "Should we continue Infra Destroy?"
            //     ok "Yes, we should"
            // }
            steps {
                sh """
                    cd 01-vpc-creation
                    terraform destroy -auto-approve
                    """
            }
        }
        
    }
    // post build
    post {
        always{
            echo 'We Will always Win again!'
        }
        failure {
            echo 'failure occured, inform the concerned teams over slack'
        }
        success {
            echo 'Confragulations on success build'
        }
    }
}