pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    
    options {
        timeout(time: 1, unit:'HOURS')
        disableConcurrentBuilds()
    }
    stages {
        stage('terraform init') {
            steps {
                sh """
                    cd 01-vpc.creation
                    terraform init -reconfigure
                    """
            }
        }
        stage('terraform plan') {
            steps {
                sh """
                    cd 01-vpc.creation
                    terraform plan
                    """
            }
        }
        stage('Apply') {
            input {
                message "Should we continue Infra Creation?"
                ok "Yes, we should"
            }
            steps {
                sh """
                    terraform apply -auto-approve
                    """
            }
        }
        stage('check params') {
            steps{
                sh """
                    echo "Hello ${params.PERSON}"
                    echo "Biography: ${params.BIOGRAPHY}"
                    echo "Toggle: ${params.TOGGLE}"
                    echo "choice: ${params.CHOICE}"
                    echo "Password: ${params.PASSWORD}"
                    echo "trigger is added"
                """
            }
        }
    }
    // post build
    post {
        always{
            echo 'We Will always Win again!'
        }
        failure {
            echo 'failure occured, inform the concerned teams over slack'
        }
        success {
            echo 'Confragulations on success build'
        }
    }
}